// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '单文件上传': typeof import('./src/components/单文件上传.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    NButton: typeof import('naive-ui')['NButton']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    NUpload: typeof import('naive-ui')['NUpload']
    SingleFileUpload: typeof import('./src/components/single-file-upload.vue')['default']
    'SingleFileUpload copy': typeof import('./src/components/single-file-upload copy.vue')['default']
  }
}

export {}
